// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHeight():Promise<number>;

export function GetPrintDirectory():Promise<string>;

export function GetPrinterDPI():Promise<main.PrinterDPI>;

export function GetPrinterPort():Promise<number>;

export function GetPrinterRunStatus():Promise<boolean>;

export function GetWidth():Promise<number>;

export function NewTCPServer():Promise<main.TCPServer>;

export function SendToLabelary(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetPrintDirectory():Promise<string>;

export function StartPrinterServer():Promise<void>;

export function StopPrintServer():Promise<void>;

export function UpdateHeight(arg1:number):Promise<void>;

export function UpdatePrinterDPI(arg1:main.PrinterDPI):Promise<void>;

export function UpdatePrinterPort(arg1:number):Promise<void>;

export function UpdateSave(arg1:boolean):Promise<void>;

export function UpdateWidth(arg1:number):Promise<void>;
