// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHeight() {
  return window['go']['main']['App']['GetHeight']();
}

export function GetPrintDirectory() {
  return window['go']['main']['App']['GetPrintDirectory']();
}

export function GetPrinterDPI() {
  return window['go']['main']['App']['GetPrinterDPI']();
}

export function GetPrinterPort() {
  return window['go']['main']['App']['GetPrinterPort']();
}

export function GetPrinterRotation() {
  return window['go']['main']['App']['GetPrinterRotation']();
}

export function GetPrinterRunStatus() {
  return window['go']['main']['App']['GetPrinterRunStatus']();
}

export function GetWidth() {
  return window['go']['main']['App']['GetWidth']();
}

export function NewTCPServer() {
  return window['go']['main']['App']['NewTCPServer']();
}

export function SendToLabelary(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendToLabelary'](arg1, arg2, arg3);
}

export function SetPrintDirectory() {
  return window['go']['main']['App']['SetPrintDirectory']();
}

export function SetPrinterRotation(arg1) {
  return window['go']['main']['App']['SetPrinterRotation'](arg1);
}

export function StartPrinterServer() {
  return window['go']['main']['App']['StartPrinterServer']();
}

export function StopPrintServer() {
  return window['go']['main']['App']['StopPrintServer']();
}

export function UpdateHeight(arg1) {
  return window['go']['main']['App']['UpdateHeight'](arg1);
}

export function UpdatePrinterDPI(arg1) {
  return window['go']['main']['App']['UpdatePrinterDPI'](arg1);
}

export function UpdatePrinterPort(arg1) {
  return window['go']['main']['App']['UpdatePrinterPort'](arg1);
}

export function UpdateSave(arg1) {
  return window['go']['main']['App']['UpdateSave'](arg1);
}

export function UpdateWidth(arg1) {
  return window['go']['main']['App']['UpdateWidth'](arg1);
}
