// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPrinter(arg1) {
  return window['go']['main']['App']['AddPrinter'](arg1);
}

export function AddRelayGroup(arg1) {
  return window['go']['main']['App']['AddRelayGroup'](arg1);
}

export function CallLabelary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CallLabelary'](arg1, arg2, arg3, arg4);
}

export function ClearPrintDirectory() {
  return window['go']['main']['App']['ClearPrintDirectory']();
}

export function DeletePrinter(arg1) {
  return window['go']['main']['App']['DeletePrinter'](arg1);
}

export function DeleteRelayGroup(arg1) {
  return window['go']['main']['App']['DeleteRelayGroup'](arg1);
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetAutoStartServer() {
  return window['go']['main']['App']['GetAutoStartServer']();
}

export function GetHeight() {
  return window['go']['main']['App']['GetHeight']();
}

export function GetPrintDirectory() {
  return window['go']['main']['App']['GetPrintDirectory']();
}

export function GetPrinterDPI() {
  return window['go']['main']['App']['GetPrinterDPI']();
}

export function GetPrinterPort() {
  return window['go']['main']['App']['GetPrinterPort']();
}

export function GetPrinterRotation() {
  return window['go']['main']['App']['GetPrinterRotation']();
}

export function GetPrinterRunStatus() {
  return window['go']['main']['App']['GetPrinterRunStatus']();
}

export function GetPrinters() {
  return window['go']['main']['App']['GetPrinters']();
}

export function GetRelayGroups() {
  return window['go']['main']['App']['GetRelayGroups']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWidth() {
  return window['go']['main']['App']['GetWidth']();
}

export function NewTCPServer() {
  return window['go']['main']['App']['NewTCPServer']();
}

export function ProcessAndSendToPrinter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessAndSendToPrinter'](arg1, arg2, arg3, arg4);
}

export function ProcessAndSendToPrinterWithIPP(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ProcessAndSendToPrinterWithIPP'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ProcessRelayGroup(arg1) {
  return window['go']['main']['App']['ProcessRelayGroup'](arg1);
}

export function SelectPrinter(arg1) {
  return window['go']['main']['App']['SelectPrinter'](arg1);
}

export function SelectRelayGroup(arg1) {
  return window['go']['main']['App']['SelectRelayGroup'](arg1);
}

export function SendToLabelary(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendToLabelary'](arg1, arg2, arg3);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetAutoStartServer(arg1) {
  return window['go']['main']['App']['SetAutoStartServer'](arg1);
}

export function SetPrintDirectory() {
  return window['go']['main']['App']['SetPrintDirectory']();
}

export function SetPrinterEmulatorMode() {
  return window['go']['main']['App']['SetPrinterEmulatorMode']();
}

export function SetPrinterRelayMode() {
  return window['go']['main']['App']['SetPrinterRelayMode']();
}

export function SetPrinterRotation(arg1) {
  return window['go']['main']['App']['SetPrinterRotation'](arg1);
}

export function SetPrinterZPLToPrinterMode() {
  return window['go']['main']['App']['SetPrinterZPLToPrinterMode']();
}

export function StartPrinterServer() {
  return window['go']['main']['App']['StartPrinterServer']();
}

export function StopPrintServer() {
  return window['go']['main']['App']['StopPrintServer']();
}

export function UpdateHeight(arg1) {
  return window['go']['main']['App']['UpdateHeight'](arg1);
}

export function UpdatePrinter(arg1) {
  return window['go']['main']['App']['UpdatePrinter'](arg1);
}

export function UpdatePrinterDPI(arg1) {
  return window['go']['main']['App']['UpdatePrinterDPI'](arg1);
}

export function UpdatePrinterPort(arg1) {
  return window['go']['main']['App']['UpdatePrinterPort'](arg1);
}

export function UpdateSave(arg1) {
  return window['go']['main']['App']['UpdateSave'](arg1);
}

export function UpdateWidth(arg1) {
  return window['go']['main']['App']['UpdateWidth'](arg1);
}
