// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function AddPrinter(arg1:main.Printer):Promise<void>;

export function AddRelayGroup(arg1:Array<number>):Promise<void>;

export function CallLabelary(arg1:string,arg2:number,arg3:number,arg4:number):Promise<http.Response>;

export function ClearPrintDirectory():Promise<void>;

export function DeletePrinter(arg1:number):Promise<void>;

export function DeleteRelayGroup(arg1:number):Promise<void>;

export function GetHeight():Promise<number>;

export function GetPrintDirectory():Promise<string>;

export function GetPrinterDPI():Promise<main.PrinterDPI>;

export function GetPrinterPort():Promise<number>;

export function GetPrinterRotation():Promise<number>;

export function GetPrinterRunStatus():Promise<boolean>;

export function GetPrinters():Promise<Array<main.Printer>>;

export function GetRelayGroups():Promise<Array<main.RelayGroup>>;

export function GetWidth():Promise<number>;

export function NewTCPServer():Promise<main.TCPServer>;

export function ProcessAndSendToPrinter(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function ProcessRelayGroup(arg1:string):Promise<void>;

export function SelectPrinter(arg1:main.Printer):Promise<void>;

export function SelectRelayGroup(arg1:main.RelayGroup):Promise<void>;

export function SendToLabelary(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetPrintDirectory():Promise<string>;

export function SetPrinterEmulatorMode():Promise<void>;

export function SetPrinterRelayMode():Promise<void>;

export function SetPrinterRotation(arg1:number):Promise<void>;

export function SetPrinterZPLToPrinterMode():Promise<void>;

export function StartPrinterServer():Promise<void>;

export function StopPrintServer():Promise<void>;

export function UpdateHeight(arg1:number):Promise<void>;

export function UpdatePrinter(arg1:main.Printer):Promise<void>;

export function UpdatePrinterDPI(arg1:main.PrinterDPI):Promise<void>;

export function UpdatePrinterPort(arg1:number):Promise<void>;

export function UpdateSave(arg1:boolean):Promise<void>;

export function UpdateWidth(arg1:number):Promise<void>;
